name 'proteon-liferay'
version '0.1.3'

author 'Proteon'
license 'Apache License, Version 2.0'
project_page 'https://github.com/Proteon/puppet-liferay'
source 'http://github.com/Proteon/puppet-liferay.git'
summary 'Puppet code for deploying and configuring Liferay in Tomcat'
description 'Puppet code for deploying and configuring Liferay in Tomcat'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'proteon/tomcat', '>=0.1.15'
dependency 'proteon/maven', '>=1.0.0'
dependency 'proteon/java', '>=0.1.6'
